name: dotnet build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *' #Executa a cada hora


jobs:
  validate-data:
    name: Validate data
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: script/validate-data/package-lock.json

      - name: Validate workflows
        run: |
          npm ci
          npx ts-node-script ./index.ts
        working-directory: ./script/validate-data

  script-personalizado:
    runs-on: ubuntu-latest
    env:
      WORKFLOW: "Workflow executado!"
    steps:
      - name: Executar linha do script
        run: echo "::add-mask::$WORKFLOW"