name: dotnet build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *' #Executa a cada hora


jobs:
  test-build-dotnet:
    name: Build dotnet
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  script-personalizado:
    runs-on: ubuntu-latest
    env:
      WORKFLOW: "Workflow executado!"
    steps:
      - name: Executar linha do script
        run: echo "::add-mask::$WORKFLOW"