name: dotnet build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *' #Executa a cada hora


jobs:
  test-build-node-js:
    name: Node.js CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  script-personalizado:
    runs-on: ubuntu-latest
    env:
      WORKFLOW: "Workflow executado!"
    steps:
      - name: Executar linha do script
        run: echo "::add-mask::$WORKFLOW"