name: dotnet build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *' #Executa a cada hora


jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        id: npm-ci
        run: npm ci 

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint  

      - name: Test
        id: npm-ci-test
        run: npm run ci-test            

  script-personalizado:
    runs-on: ubuntu-latest
    env:
      WORKFLOW: "Workflow executado!"
    steps:
      - name: Executar linha do script
        run: echo "::add-mask::$WORKFLOW"