name: dotnet build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *' #Executa a cada hora


jobs:
  test-build-docker-image:
    name: Build the Docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  script-personalizado:
    runs-on: ubuntu-latest
    env:
      WORKFLOW: "Workflow executado!"
    steps:
      - name: Executar linha do script
        run: echo "::add-mask::$WORKFLOW"